//! match_events 全体のユニットテスト。

use super::{actions, contacts, punishes};

mod contact_does_not_bridge_meter_reset_epochs;
mod damage_sequence_uses_gameplay_gap_across_sa_freeze;
mod drive_impact_invincible_start_is_confirmed;
mod empty_input_produces_an_empty_event_model;
mod health_bookkeeping;
mod legacy_input_segment_defaults_to_direct_observation;
mod punish_does_not_bridge_meter_reset_epochs;
mod sustained_burnout_is_reported_and_clipped_to_its_round;
mod test_contact_extraction_hit_and_block;
mod test_contact_projectile_flag;
mod test_damage_sequences;
mod test_jump_landed_hit_excludes_post_landing_damage;
mod test_jump_outcome;
mod test_jump_outcome_by_contact_windows;
mod test_one_contact_is_assigned_to_the_nearest_jump_only;
mod test_pre_freeze_anchor;
mod test_punish_excludes_blocked_and_own_sa;
mod test_punish_missed_needs_block;
mod test_reversal_and_guard_break;
mod test_round_split_and_winner;
mod test_segments_split_on_input_change;
mod test_state_per_frame_maps_motion_recovery_and_projectile;
mod test_throw_connected;
mod test_throw_escape_not_reversal;
mod throw_action_links_delayed_damage_and_deduplicates_held_input;
mod throw_input_without_matching_execution_is_unconfirmed;
mod throw_loses_to_invincible_reversal;
mod timeline_projections_clip_entries_and_apply_later_overlaps;
mod whole_match_pipeline;

pub(super) use crate::test_support as support;
