//! advice 全体のユニットテスト。

use super::damage_origins;

mod a_single_jump_exchange_is_observed_but_not_called_a_habit;
mod backward_jump_hit_does_not_emit_approach_advice;
mod cause_specific_observation_owns_the_same_big_damage;
mod committed_button_vs_di;
mod damage_breakdown_is_exclusive_and_preserves_all_damage;
mod damage_breakdown_matches_official_modern_low_with_meter_startup;
mod damage_breakdown_prefers_compound_threat_and_adds_advice_context;
mod detector_coverage;
mod diagnoses_sort_before_higher_severity_observations;
mod input_stats_and_coverage_use_only_validated_rounds;
mod legacy_card_without_classification_deserializes_conservatively;
mod low_punish_return_must_repeat_before_it_is_a_diagnosis;
mod mashing_attributes_the_nearest_press;
mod mashing_requires_direct_input_and_reliable_linked_startup;
mod one_early_hit_is_kept_as_an_observation;
mod repeated_guard_direction_and_reversal_are_required_for_diagnosis;
mod single_minus_read_loss_is_observed_but_not_called_a_habit;
mod super_art_stats_and_advice;
mod tactic_stats_only_count_confirmed_interactions;
mod test_anti_air_card;
mod test_big_hits_card;
mod test_burnout_card;
mod test_layered_defense_card_requires_short_parry_and_damage;
mod test_lead_loss_clip_range;
mod test_mashing_excludes_beaten_by_invincible;
mod test_mashing_excludes_jump_attributed_damage;
mod test_mashing_excludes_minus_press_attributed;
mod test_mashing_excludes_own_raw_drive_rush;
mod test_mashing_excludes_projectile_press;
mod test_mashing_ignores_projectile_block_context;
mod test_naked_teleport_card_requires_confirmed_reach;
mod test_press_while_minus_card;
mod test_punish_fail_card_requires_confirmed_reach;
mod test_punish_missed_card_requires_confirmed_reach;
mod test_throw_loop_needs_streak;
mod test_throw_whiff_punished;
mod test_throw_while_minus_has_its_own_card;

mod support;
