use super::*;
use crate::match_events::{CompoundThreat, TeleportEvent, ThreatOutcome};
use crate::{
    AnalysisContext, DefenseResponse, DpReachability, DriveRushEvent, DriveRushOutcome,
    EventConfidence, JumpDirection, JumpOutcome, MatchEvents, ProjectileThreat, PunishChance,
    PunishOrigin, PunishOutcome, PunishReachability, RoundInfo, TeleportContext, ThrowApproach,
    ThrowOutcome,
};

mod airborne_region_requires_jump_hint_for_ground_track;
mod approach_windows_are_clipped_to_the_round;
mod confirmed_drive_rush_is_preferred_as_the_throw_approach;
mod confirms_small_moving_object_trajectory;
mod far_reacquire_requires_explicit_discontinuity_hint;
mod forward_dash_throw_requires_forward_inputs_and_distance_closing;
mod grounded_contact_is_not_kept_as_an_anti_air;
mod jump_contact_gets_a_short_spatial_window;
mod landed_hit_requires_airborne_evidence_until_contact;
mod missed_punish_gets_a_short_spatial_window;
mod missed_punish_reach_requires_overlap;
mod naked_teleport_reach_requires_character_profile_and_overlap;
mod overlay_exclusions_remove_changing_meter_region;
mod projectile_trajectory_confidence_propagates_to_compound_threat;
mod rejects_short_rgba_buffer;
mod reset_allows_a_new_frame_size_after_rejecting_dimension_changes;
mod semantic_windows_merge_and_keep_event_hints;
mod spatial_observation_json_keeps_the_wasm_contract;
mod strike_whiff_accepts_stable_mid_but_rejects_far;
mod strike_whiff_gets_a_window_through_its_active_frame;
mod support;
mod tracks_actor_anchors_and_distance_band;

use support::*;
