//! advice 全体のユニットテスト。

use super::damage_origins;

mod cause_specific_observation_owns_the_same_big_damage;
mod damage_breakdown_is_exclusive_and_preserves_all_damage;
mod damage_breakdown_matches_official_modern_low_with_meter_startup;
mod damage_breakdown_prefers_compound_threat_and_adds_advice_context;
mod decision_projection_matches_source_events;
mod detector_coverage;
mod diagnoses_sort_before_higher_severity_observations;
mod input_stats_and_coverage_use_only_validated_rounds;
mod legacy_card_without_classification_deserializes_conservatively;
mod single_minus_read_loss_is_observed_but_not_called_a_habit;
mod super_art_stats_and_advice;
mod test_anti_air_card;
mod test_big_hits_card;
mod test_burnout_card;
mod test_mashing_excludes_beaten_by_invincible;
mod test_mashing_excludes_jump_attributed_damage;
mod test_mashing_excludes_minus_press_attributed;
mod test_mashing_excludes_projectile_press;
mod test_mashing_ignores_projectile_block_context;
mod test_press_while_minus_card;
mod test_throw_loop_needs_streak;
mod test_throw_whiff_punished;
mod test_throw_while_minus_has_its_own_card;

mod report_wiring;
mod support;
