use super::*;
use crate::match_events::{CompoundThreat, ThreatOutcome};
use crate::{
    AnalysisContext, DpReachability, DriveRushEvent, DriveRushOutcome, EventConfidence,
    JumpDirection, JumpOutcome, ProjectileThreat, PunishChance, PunishOrigin, PunishOutcome,
    PunishReachability, ThrowApproach, ThrowOutcome,
};

mod airborne_region_requires_jump_hint_for_ground_track;
mod approach_windows_are_clipped_to_the_round;
mod certain_side_hints_follow_round_opens;
mod cold_guard_spark_yields_contact_point;
mod confirmed_drive_rush_is_preferred_as_the_throw_approach;
mod confirms_small_moving_object_trajectory;
mod contact_hint_keeps_effect_region_off_actor_tracks;
mod contact_hint_ranges_follow_first_stage_contacts;
mod contact_hint_yields_spark_centroid;
mod contact_spark_requires_hint_and_actor_span;
mod corner_spans_follow_the_camera_clamp;
mod coverage_records_candidate_and_sampled_frames;
mod disruption_extends_the_contact_search;
mod embedded_spark_is_found_inside_a_body_region;
mod far_reacquire_requires_explicit_discontinuity_hint;
mod forward_dash_throw_requires_forward_inputs_and_distance_closing;
mod grounded_contact_is_not_kept_as_an_anti_air;
mod high_contact_spark_confirms_an_airborne_hit;
mod initial_airborne_hint_assigns_crossed_actor;
mod jump_contact_gets_a_short_spatial_window;
mod landed_hit_requires_airborne_evidence_until_contact;
mod learned_colors_resolve_a_crossed_window_start;
mod missed_punish_gets_a_short_spatial_window;
mod missed_punish_reach_requires_overlap;
mod naked_teleport_reach_requires_character_profile_and_overlap;
mod overlay_exclusions_remove_changing_meter_region;
mod projectile_trajectory_confidence_propagates_to_compound_threat;
mod rejects_short_rgba_buffer;
mod reset_allows_a_new_frame_size_after_rejecting_dimension_changes;
mod semantic_windows_merge_and_keep_event_hints;
mod shadow_cluster_snaps_the_actor_anchor;
mod spatial_observation_json_keeps_the_wasm_contract;
mod still_appearance_confirms_a_frozen_actor;
mod strike_whiff_gets_a_window_through_its_active_frame;
use crate::test_support as support;
mod tracks_actor_anchors_and_distance_band;
mod zoom_correction_reveals_hidden_approach;

use support::*;
