import { afterEach, describe, expect, test } from "bun:test";
import {
  mkdir,
  mkdtemp,
  readFile,
  rm,
  symlink,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  compareArtifactIdentity,
  compareFixtureIdSets,
  computeArtifactIdentity,
  parseBaselineArtifact,
  REQUIRED_PERFORMANCE_STAGES,
  RUNNER_VERSION,
  summarizeSpatialPerformanceStats,
} from "./local-video-e2e-baseline";
import {
  assertBaselineAnalyzedFileBinding,
  beginOutputTransaction,
  prepareOutputDirectories,
} from "./local-video-e2e-output";

const SHA = "a".repeat(64);
const temporaryDirectories: string[] = [];

afterEach(async () => {
  await Promise.all(
    temporaryDirectories
      .splice(0)
      .map((directory) => rm(directory, { recursive: true, force: true })),
  );
});

async function temporaryDirectory(): Promise<string> {
  const directory = await mkdtemp(join(tmpdir(), "fighter-notes-e2e-test-"));
  temporaryDirectories.push(directory);
  return directory;
}

function performance() {
  return {
    runsMs: [100, 100, 100],
    medianMs: 100,
    p90Ms: 100,
    stages: Object.fromEntries(
      REQUIRED_PERFORMANCE_STAGES.map((stage) => [
        stage,
        { medianMs: 10, p90Ms: 10 },
      ]),
    ),
  };
}

function artifact(): Record<string, unknown> {
  return {
    schemaVersion: 2,
    runnerVersion: RUNNER_VERSION,
    caseId: "fixture-a",
    videoName: "replay.mp4",
    fixtureContract: {
      fixtureFingerprint: SHA,
      settings: {
        side: "p1",
        ownCharacter: "KEN",
        opponentCharacter: "JURI",
      },
      expectationHash: SHA,
    },
    analysisMs: 100,
    performance: performance(),
    spatialPerformance: {
      frameCount: 1_001,
      decoderQueueHighWatermark: 12,
      decoderQueueLowWatermark: 6,
      decoderOutstandingHighWatermark: 12,
      decoderOutstandingLowWatermark: 6,
      workerPendingHighWatermark: 12,
      workerPendingLowWatermark: 6,
      peakDecoderQueueSize: 12,
      peakDecoderOutstandingFrames: 12,
      peakWorkerPendingFrames: 12,
    },
    report: { analyzer_build_id: "build-a", rounds_detected: 2 },
    timeline: { left: [], right: [] },
    hpFeatures: [],
    trackedInputs: { p1: [], p2: [] },
    fightMarkers: [],
    attackInfo: [],
    regressionEvents: {
      rounds: [],
      damage: [],
      super_arts: [],
      attack_evidence: { sequences: [], damage: [], super_arts: [] },
    },
    spatialWindows: [],
    spatialObservations: [],
    perfLogs: [],
  };
}

describe("local video E2E baseline identity", () => {
  test("requires the current and baseline fixture sets to be identical", () => {
    expect(compareFixtureIdSets(["a", "b"], ["a", "b"])).toEqual([]);
    expect(compareFixtureIdSets(["a"], ["a", "b"])).toEqual([
      "baseline fixture b is missing from the current manifest",
    ]);
    expect(compareFixtureIdSets(["a", "b"], ["a"])).toEqual([
      "current fixture b is missing from the baseline",
    ]);
    expect(compareFixtureIdSets(["a", "a"], ["a", "a"])).toEqual([
      "current manifest contains duplicate fixture id a",
      "baseline contains duplicate fixture id a",
    ]);
  });

  test("strictly parses a baseline artifact contract", () => {
    expect(parseBaselineArtifact(artifact(), "fixture-a.json", 3).caseId).toBe(
      "fixture-a",
    );
    expect(() =>
      parseBaselineArtifact(
        { ...artifact(), unexpected: true },
        "fixture-a.json",
        3,
      ),
    ).toThrow("fields must be");
    expect(() =>
      parseBaselineArtifact(
        { ...artifact(), regressionEvents: [] },
        "fixture-a.json",
        3,
      ),
    ).toThrow("regressionEvents must be an object");
    expect(() =>
      parseBaselineArtifact(
        { ...artifact(), runnerVersion: RUNNER_VERSION - 1 },
        "fixture-a.json",
        3,
      ),
    ).toThrow("was not generated by this runner");
    expect(() =>
      parseBaselineArtifact(
        {
          ...artifact(),
          spatialPerformance: {
            ...(artifact().spatialPerformance as object),
            peakWorkerPendingFrames: 13,
          },
        },
        "fixture-a.json",
        3,
      ),
    ).toThrow("exceeds its high watermark");
    const missingStage = artifact();
    const timing = missingStage.performance as ReturnType<typeof performance>;
    const { meterWasm: _missing, ...stages } = timing.stages;
    expect(() =>
      parseBaselineArtifact(
        { ...missingStage, performance: { ...timing, stages } },
        "fixture-a.json",
        3,
      ),
    ).toThrow("stages.meterWasm is required");
  });

  test("rejects a stale or replaced full artifact against summary hashes", () => {
    const original = artifact();
    const identity = computeArtifactIdentity(original);
    expect(compareArtifactIdentity(original, identity)).toEqual([]);

    const changed = {
      ...original,
      report: { analyzer_build_id: "build-a", rounds_detected: 3 },
    };
    expect(compareArtifactIdentity(changed, identity)).toEqual([
      "capture hash report does not match summary",
      "semantic hash does not match summary",
    ]);

    const performanceOnly = {
      ...original,
      spatialPerformance: {
        ...(original.spatialPerformance as object),
        peakWorkerPendingFrames: 11,
      },
    };
    expect(compareArtifactIdentity(performanceOnly, identity)).toEqual([]);
  });

  test("keeps stable spatial work and the highest peak across measured runs", () => {
    const first = artifact().spatialPerformance as Parameters<
      typeof summarizeSpatialPerformanceStats
    >[0][number];
    expect(
      summarizeSpatialPerformanceStats(
        [first, { ...first, peakWorkerPendingFrames: 11 }],
        "spatial",
      ).peakWorkerPendingFrames,
    ).toBe(12);
    expect(() =>
      summarizeSpatialPerformanceStats(
        [first, { ...first, frameCount: first.frameCount - 1 }],
        "spatial",
      ),
    ).toThrow("frameCount changed");
  });
});

describe("local video E2E output integrity", () => {
  test("rejects an unverified browser-side path for baseline comparison", () => {
    expect(() =>
      assertBaselineAnalyzedFileBinding("fixture-a", "D:\\replays\\a.mp4"),
    ).toThrow(
      "fixture-a: baseline comparison cannot verify browserVideoPath content against videoPath",
    );
    expect(() =>
      assertBaselineAnalyzedFileBinding("fixture-a", undefined),
    ).not.toThrow();
  });

  test("rejects a symlink alias between baseline and output", async () => {
    const root = await temporaryDirectory();
    const baseline = join(root, "baseline");
    const outputAlias = join(root, "current");
    await mkdir(baseline);
    await symlink(baseline, outputAlias, "dir");

    await expect(
      prepareOutputDirectories(outputAlias, baseline),
    ).rejects.toThrow(
      "--baseline and --output must be different physical directories",
    );
  });

  test("rejects nested baseline and output directories", async () => {
    const root = await temporaryDirectory();
    const output = join(root, "current");
    const nestedBaseline = join(output, "baseline");
    await mkdir(nestedBaseline, { recursive: true });

    await expect(
      prepareOutputDirectories(output, nestedBaseline),
    ).rejects.toThrow(
      "--baseline and --output must not contain one another physically",
    );
  });

  test("keeps the previous output until a complete staged run is published", async () => {
    const root = await temporaryDirectory();
    const output = join(root, "current");
    await prepareOutputDirectories(output);
    await writeFile(join(output, "summary.json"), "old summary");
    await writeFile(join(output, "old-case.json"), "old case");

    const incomplete = await beginOutputTransaction(output);
    await writeFile(join(incomplete.directory, "new-case.json"), "new case");
    await expect(incomplete.publish()).rejects.toThrow(
      "staged E2E output is incomplete",
    );
    expect(await readFile(join(output, "summary.json"), "utf8")).toBe(
      "old summary",
    );
    await incomplete.discard();

    const complete = await beginOutputTransaction(output);
    await writeFile(join(complete.directory, "new-case.json"), "new case");
    await writeFile(join(complete.directory, "summary.json"), "new summary");
    expect(await readFile(join(output, "summary.json"), "utf8")).toBe(
      "old summary",
    );
    await complete.publish();

    expect(await readFile(join(output, "summary.json"), "utf8")).toBe(
      "new summary",
    );
    expect(await readFile(join(output, "new-case.json"), "utf8")).toBe(
      "new case",
    );
    await expect(
      readFile(join(output, "old-case.json"), "utf8"),
    ).rejects.toThrow();
  });
});
