import { describe, expect, test } from "bun:test";
import {
  compareArtifactIdentity,
  compareFixtureIdSets,
  computeArtifactIdentity,
  parseBaselineArtifact,
  REQUIRED_PERFORMANCE_STAGES,
  RUNNER_VERSION,
} from "./local-video-e2e-baseline";

const SHA = "a".repeat(64);

function performance() {
  return {
    runsMs: [100, 100, 100],
    medianMs: 100,
    p90Ms: 100,
    stages: Object.fromEntries(
      REQUIRED_PERFORMANCE_STAGES.map((stage) => [
        stage,
        { medianMs: 10, p90Ms: 10 },
      ]),
    ),
  };
}

function artifact(): Record<string, unknown> {
  return {
    schemaVersion: 2,
    runnerVersion: RUNNER_VERSION,
    caseId: "fixture-a",
    videoName: "replay.mp4",
    fixtureContract: {
      fixtureFingerprint: SHA,
      settings: {
        side: "p1",
        ownCharacter: "KEN",
        opponentCharacter: "JURI",
      },
      expectationHash: SHA,
    },
    analysisMs: 100,
    performance: performance(),
    report: { analyzer_build_id: "build-a", rounds_detected: 2 },
    timeline: { left: [], right: [] },
    hpFeatures: [],
    trackedInputs: { p1: [], p2: [] },
    fightMarkers: [],
    attackInfo: [],
    regressionEvents: {
      rounds: [],
      damage: [],
      super_arts: [],
      attack_evidence: { sequences: [], damage: [], super_arts: [] },
    },
    spatialWindows: [],
    spatialObservations: [],
    perfLogs: [],
  };
}

describe("local video E2E baseline identity", () => {
  test("requires the current and baseline fixture sets to be identical", () => {
    expect(compareFixtureIdSets(["a", "b"], ["a", "b"])).toEqual([]);
    expect(compareFixtureIdSets(["a"], ["a", "b"])).toEqual([
      "baseline fixture b is missing from the current manifest",
    ]);
    expect(compareFixtureIdSets(["a", "b"], ["a"])).toEqual([
      "current fixture b is missing from the baseline",
    ]);
    expect(compareFixtureIdSets(["a", "a"], ["a", "a"])).toEqual([
      "current manifest contains duplicate fixture id a",
      "baseline contains duplicate fixture id a",
    ]);
  });

  test("strictly parses a baseline artifact contract", () => {
    expect(parseBaselineArtifact(artifact(), "fixture-a.json", 3).caseId).toBe(
      "fixture-a",
    );
    expect(() =>
      parseBaselineArtifact(
        { ...artifact(), unexpected: true },
        "fixture-a.json",
        3,
      ),
    ).toThrow("fields must be");
    expect(() =>
      parseBaselineArtifact(
        { ...artifact(), regressionEvents: [] },
        "fixture-a.json",
        3,
      ),
    ).toThrow("regressionEvents must be an object");
    expect(() =>
      parseBaselineArtifact(
        { ...artifact(), runnerVersion: RUNNER_VERSION - 1 },
        "fixture-a.json",
        3,
      ),
    ).toThrow("was not generated by this runner");
    const missingStage = artifact();
    const timing = missingStage.performance as ReturnType<typeof performance>;
    const { meterWasm: _missing, ...stages } = timing.stages;
    expect(() =>
      parseBaselineArtifact(
        { ...missingStage, performance: { ...timing, stages } },
        "fixture-a.json",
        3,
      ),
    ).toThrow("stages.meterWasm is required");
  });

  test("rejects a stale or replaced full artifact against summary hashes", () => {
    const original = artifact();
    const identity = computeArtifactIdentity(original);
    expect(compareArtifactIdentity(original, identity)).toEqual([]);

    const changed = {
      ...original,
      report: { analyzer_build_id: "build-a", rounds_detected: 3 },
    };
    expect(compareArtifactIdentity(changed, identity)).toEqual([
      "capture hash report does not match summary",
      "semantic hash does not match summary",
    ]);
  });
});
