//! 検出器の契約に対するテスト。
//!
//! 観測列の組み立てはイベント層の test-support から借りる。

mod support;

mod a_single_jump_exchange_is_observed_but_not_called_a_habit;
mod backward_jump_hit_does_not_emit_approach_advice;
mod committed_button_vs_di;
mod drive_impact_gates;
mod low_punish_return_must_repeat_before_it_is_a_diagnosis;
mod mashing_attributes_the_nearest_press;
mod mashing_gates;
mod mashing_pressure;
mod mashing_requires_direct_input_and_reliable_linked_startup;
mod one_early_hit_is_kept_as_an_observation;
mod repeated_guard_direction_and_reversal_are_required_for_diagnosis;
mod test_layered_defense_card_requires_short_parry_and_damage;
mod test_lead_loss_clip_range;
mod test_mashing_excludes_own_raw_drive_rush;
mod test_naked_teleport_card_requires_confirmed_reach;
mod test_punish_fail_card_requires_confirmed_reach;
mod test_punish_missed_card_requires_confirmed_reach;
