use video_analyzer::{
    ActorHint, ActorObservation, AdviceCard, AdviceKind, AdviceReport, AnalysisContext,
    AttributedDamageEvent, BadgeColor, BadgeMark, BurnoutCause, BurnoutPeriod, CompoundThreat,
    ContactEvent, DamageBreakdown, DamageContext, DamageEvent, DamageOrigin, DamageTakenEvent,
    DefenseResponse, DefenseResponseKind, DefensiveActionKind, DistanceBand, DpReachability,
    DriveGaugeRead, DriveImpactEvent, DriveImpactOutcome, DriveRushEvent, DriveRushOutcome,
    EventConfidence, EvidenceClip, FrameFeatures, GuardBreakEvent, HorizontalMotion,
    HorizontalOrder, HpParallelogram, InputDir, InputRow, InputStats, JumpDirection, JumpEvent,
    JumpOutcome, MatchEvents, MeterState, MinusPressEvent, MinusPressOutcome, MinusSituationEvent,
    MotionRegionObservation, PlayerContext, ProjectileCandidate, ProjectileThreat, PunishChance,
    PunishOrigin, PunishOutcome, PunishReachability, ReversalEvent, RoundInfo, RoundSummary,
    SpatialCandidateWindow, SpatialConfig, SpatialError, SpatialExtractor, SpatialHintRange,
    SpatialHints, SpatialObservation, SpatialPoint, SpatialRect, StrikeKind, TacticStats,
    TeleportContext, TeleportEvent, ThreatOutcome, ThrowActionEvent, ThrowApproach, ThrowEvent,
    ThrowOutcome, TrackedInput, Weakness,
};

macro_rules! assert_types_exist {
    ($($type:ty),+ $(,)?) => { $(let _ = std::mem::size_of::<$type>();)+ };
}

#[test]
fn crate_root_keeps_public_model_names() {
    assert_types_exist!(
        ActorHint,
        ActorObservation,
        AdviceCard,
        AdviceKind,
        AdviceReport,
        AnalysisContext,
        AttributedDamageEvent,
        BadgeColor,
        BadgeMark,
        BurnoutCause,
        BurnoutPeriod,
        CompoundThreat,
        ContactEvent,
        DamageBreakdown,
        DamageContext,
        DamageEvent,
        DamageOrigin,
        DamageTakenEvent,
        DefenseResponse,
        DefenseResponseKind,
        DefensiveActionKind,
        DistanceBand,
        DpReachability,
        DriveGaugeRead,
        DriveImpactEvent,
        DriveImpactOutcome,
        DriveRushEvent,
        DriveRushOutcome,
        EventConfidence,
        EvidenceClip,
        FrameFeatures,
        GuardBreakEvent,
        HorizontalMotion,
        HorizontalOrder,
        HpParallelogram,
        InputDir,
        InputRow,
        InputStats,
        JumpDirection,
        JumpEvent,
        JumpOutcome,
        MatchEvents,
        MeterState,
        MinusPressEvent,
        MinusPressOutcome,
        MinusSituationEvent,
        MotionRegionObservation,
        PlayerContext,
        ProjectileCandidate,
        ProjectileThreat,
        PunishChance,
        PunishOrigin,
        PunishOutcome,
        PunishReachability,
        ReversalEvent,
        RoundInfo,
        RoundSummary,
        SpatialCandidateWindow,
        SpatialConfig,
        SpatialError,
        SpatialExtractor,
        SpatialHintRange,
        SpatialHints,
        SpatialObservation,
        SpatialPoint,
        SpatialRect,
        StrikeKind,
        TacticStats,
        TeleportContext,
        TeleportEvent,
        ThreatOutcome,
        ThrowActionEvent,
        ThrowApproach,
        ThrowEvent,
        ThrowOutcome,
        TrackedInput,
        Weakness,
    );
}
